### ISSUE TITLE
Removing i18n files from output of enact pack?

### ISSUE THREAD

**Issue by bongsok** [enactjs/cli#156]
Is there any way in `enact cli` to remove i18n files in order to reduce size of output? I'm making my app in Korean only but these files are always included in `dist` and they are much huge compared to `main.js` and `main.css`.

**Comment by JayCanuck** [comment]
You can set an absolute path for ilib to be expected at via `ILIB_BASE_PATH` environment variable. For example,
```
export ILIB_BASE_PATH="/usr/share/javascript/ilib"
enact pack
```
That will omit ilib and configure `@enact/i18n` (and by extension @enact/moonstone) to load ilib json assets from that location.

The `ILIB_BASE_PATH` environment variable can also be set to a relative path, though that will still copy files and expect ilib assets to exist at build-time from that location.

Aside from that, to remove i18n files entirely, the i18n library, and it's depended libraries (moonstone, etc.) would need to be removed entirely.

**Comment by webOS101** [comment]
Would it be possible to extend the usage fo the `--locales` option to only copy the associated ilib resources for the specified locales?

**Comment by JayCanuck** [comment]
Potentially, though we'd need a map of which timezones/locales/unit formats, etc correspond to the desired locales. Not a simple clear-cut solution.

**Comment by JayCanuck** [comment]
`--locales` is for specifying which locales to prerender for.

**Comment by bongsok** [comment]
May I ask you have any plan to give an option to turn off i18n with pack in the future?

**Comment by webOS101** [comment]
That would be a good enhancement and we'll look at that for a future release.
