### ISSUE TITLE
Error run serve

### ISSUE THREAD

**Issue by RichardNTran** [enactjs/cli#182]
I create new project, after then run enact eject and package.json will be change 
"scripts": {
    "serve": "node ./scripts/serve.js",
    "pack": "node ./scripts/pack.js",

But when run npm run serve which will show error 'SyntaxError:  Unexpected token (19:2)
'  at  App.js
Please help me check it again! Maybe outupdate.
Current version enact cli: 2.0.2
Version enact in package.json:
"dependencies": {
    "@babel/polyfill": "7.2.5",
    "@enact/core": "^2.0.0",
    "@enact/i18n": "^2.0.0",
    "@enact/moonstone": "^2.0.0",
    "@enact/spotlight": "^2.0.0",
    "@enact/ui": "^2.0.0",
    "prop-types": "^15.6.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "devDependencies": {
    "@babel/core": "7.2.2",
    "@babel/plugin-proposal-class-properties": "7.3.0",
    "@babel/plugin-proposal-export-default-from": "7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "7.2.0",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-react-inline-elements": "7.2.0",
    "@babel/preset-env": "7.3.1",
    "@babel/preset-react": "7.0.0",
    "@babel/preset-typescript": "7.1.0",
    "@enact/dev-utils": "2.1.0",
    "@enact/template-moonstone": "2.3.1",
    "acorn": "^6.0.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "24.1.0",
    "babel-loader": "8.0.5",
    "babel-plugin-dev-expression": "0.2.1",
    "babel-plugin-dynamic-import-node": "2.2.0",
    "case-sensitive-paths-webpack-plugin": "2.2.0",
    "chai": "4.2.0",
    "chalk": "2.4.2",
    "cross-spawn": "6.0.5",
    "css-loader": "2.1.0",
    "dotenv": "6.2.0",
    "dotenv-expand": "4.2.0",
    "enzyme": "3.8.0",
    "enzyme-adapter-react-16": "1.9.1",
    "eslint": "5.13.0",
    "eslint-config-enact": "1.4.1",
    "eslint-loader": "2.1.2",
    "eslint-plugin-babel": "5.3.0",
    "eslint-plugin-enact": "0.1.3",
    "eslint-plugin-jest": "22.3.0",
    "eslint-plugin-react": "7.12.4",
    "expose-loader": "0.7.5",
    "file-loader": "3.0.1",
    "filesize": "4.0.0",
    "fork-ts-checker-webpack-plugin-alt": "0.4.14",
    "fs-extra": "7.0.1",
    "html-webpack-plugin": "4.0.0-alpha",
    "identity-obj-proxy": "3.0.0",
    "jest": "24.1.0",
    "less": "3.9.0",
    "less-loader": "4.1.0",
    "license-checker": "25.0.1",
    "mini-css-extract-plugin": "0.5.0",
    "minimist": "1.2.0",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-global-import": "1.0.6",
    "postcss-loader": "3.0.0",
    "postcss-preset-env": "6.5.0",
    "postcss-resolution-independence": "1.0.0",
    "raw-loader": "1.0.0",
    "react-dev-utils": "7.0.3",
    "react-test-renderer": "16.8.1",
    "resolution-independence": "1.0.0",
    "resolve": "1.10.0",
    "strip-ansi": "5.0.0",
    "style-loader": "0.23.1",
    "terser-webpack-plugin": "1.2.2",
    "webpack": "4.29.3",
    "webpack-dev-server": "3.1.14"
  }

**Comment by webOS101** [comment]
Hi Richard!  Thanks for the bug report.  I was able to duplicate this bug.  We'll get back to you with a workaround or an update on when it will be fixed soon!

**Comment by JayCanuck** [comment]
A fix has been pushed into PR.  A workaround that can be applied to existing projects is to open `./config/babelrc.js` and update it to be a function returning the config object (with an added api cache call):

```
const app = require('@enact/dev-utils').optionParser;

module.exports = function (api) {
	const env = process.env.BABEL_ENV || process.env.NODE_ENV;
	const es5Standalone = process.env.ES5 && process.env.ES5 !== 'false';

	api.cache(() => env + es5Standalone);

	return {
		presets: [
			[
				'@babel/preset-env',
				{
					exclude: [
						'transform-regenerator',
						'web.dom-collections.for-each',
						'web.dom-collections.iterator',
						'web.immediate',
						'web.queue-microtask',
						'web.timers',
						'web.url',
						'web.url.to-json',
						'web.url-search-params'
					],
					forceAllTransforms: es5Standalone,
					useBuiltIns: 'entry',
					corejs: 3,
					modules: false
				}
			],
			[
				'@babel/preset-react',
				{
		 			development: env !== 'production' && !es5Standalone,
					useBuiltIns: true
				}
			],
			[
				'@babel/preset-typescript'
			]
		],
		plugins: [
			'@babel/plugin-proposal-export-default-from',
			'@babel/plugin-proposal-export-namespace-from',
			'@babel/plugin-syntax-dynamic-import',
			['@babel/plugin-proposal-class-properties', { 'loose': true }],
			'dev-expression',
			env === 'production' && !es5Standalone && '@babel/plugin-transform-react-inline-elements'
		].filter(Boolean)
	};
};
```

**Comment by JayCanuck** [comment]
Just as an update, CLI 2.2.0 is now on NPM with the ejection fix.  Try it out; we can close this issue if it's working for you. We'd also love hear more about why you decided to eject the app in the first place, to find out if there's some common use-case we should integrate built-in.

**Comment by JayCanuck** [comment]
Closing out as it should be fixed across stable CLI release.
