### ISSUE TITLE
enact create doesn't create a webos-meta folder?

### ISSUE THREAD

**Issue by mattylase** [enactjs/cli#210]
I'm following the tutorial at https://enactjs.com/docs/tutorials/setup/ to do some development on webOS.

As a sanity check, I'm just trying to install the very basic app that's generated by `enact create my-app`. 

However, `npm pack` just creates a `.tgz` (perhaps to be expected), and `ares-package ./my-app` yields `ares-package ./my-app
ares-package ERR! *** ares-package: ERROR: '/Users/lase/Code/my-app' has no meta files such as appinfo.json`.

Am I missing something? Do I need to add additional flags to generate the meta folder?

**Comment by webOS101** [comment]
Hi Matt!  The command you want to use is:

```
npm run pack
```

`npm pack` is a completely different beast.

**Comment by webOS101** [comment]
Additionally, the default theme does not include the resource files for webOS.  You may want to try using the webOS template:  https://github.com/enactjs/templates/tree/master/packages/webostv/template or copy the `webos-meta` folder from there into your app.

**Comment by sugardave** [comment]
You can also use `ares-generate` to create the application info required for `ares-package` to work, though it will be in a different structure.  `ares-generate` will put it in the root of your project instead.

You could _probably_ move it into a `webos-meta` directory after that, but I haven't tested it.  If you're just starting, it's  probably easier to start over using the `webostv` template like @webOS101 said.

**Comment by mattylase** [comment]
Thanks so much @webOS101 and @sugardave for the timely responses! Looks like the template was just what I was looking for! If either of you have access, it might be worth updating the [docs on the site](https://enactjs.com/docs/tutorials/setup/), since that indicates you'll wind up with a `/webos-meta` folder using the vanilla `enact create app`.

For a sanity check, the build process would look like this, correct?

- `npm run pack`
- `ares-package /dist`

**Comment by webOS101** [comment]
Oops!  You're right, that should be removed.  That build process looks correct.
