### ISSUE TITLE
https serve is not working

### ISSUE THREAD

**Issue by uuuuuup** [enactjs/cli#228]
hi

in serve.js
function devServerConfig(host, protocol, publicPath, proxy, allowedHost) {
	let https = false;
	const {SSL_CRT_FILE, SSL_KEY_FILE} = process.env;
	if (protocol === 'https' && [SSL_CRT_FILE, SSL_KEY_FILE].all(f => f && fs.existsSync(f))) {

all()  is correct?
it should be changed to every().

Thanks.

**Comment by MikyungKim** [comment]
This issue is resolved in 3.0.5,
