### ISSUE TITLE
Hot reload changed locale files

### ISSUE THREAD

**Issue by duc10-nguyen** [enactjs/cli#328]
Hi enact team,

I'm writing an enact app, it supports 2 languages. Every time I make changes in localization files (strings.json) and save, nothing happens, the changes not reload directly, so I have to `enact serve` again.
Is it possible to update locales without restarting node server? It's better if enact-cli could support this.

Thanks.

**Comment by hong6316** [comment]
I will check the hot reload and reply to you here.
Until then, use `Refresh(F5)` on the browser or do `enact serve` again.

**Comment by hong6316** [comment]
Unfortunately, no hot reload is currently available for changes to localization files (string.json).
Hot reload is provided when you change the .js or .css file.
I will check the availability of support in the future through the status of the webpack update and internal review within the Enact team.

Thanks.
